export enum SocketMethods {
  JOIN = 'join',
  LEAVE = 'leave',
  CLICK = 'click',
  UPVOTE = 'upvote',
  REFRESH = 'refresh',
  VOTE = 'vote',
  CONNECTION = 'connection',
  CANCEL_VOTE = 'cancel-vote',
  GET_COMMENTS = 'get-comments',
  GET_INCIDENT = 'get-incident',
  ADD_USER_GEO = 'add-user-geo',
  GET_USER_GEO = 'get-users-geo',
  GET_INCIDENTS = 'get-incidents',
  CREATE_REPORT = 'create-report',
  CREATE_COMMENT = 'create-comment',
  DELETE_COMMENT = 'delete-comment',
  DELETE_INCIDENT = 'delete-incident',
  CREATE_INCIDENT = 'create-incident',
  SEND_NOTIFICATION = 'send-notification',
  GET_GEO_INCIDENTS = 'get-geojson-incidents',
  GET_SCHEDULED_INC = 'get-scheduled-incidents',
  GET_DELETED_INCIDENTS_ON_MAP = 'deleted-incidents',
}
